# Site settings
title: GestureWei Blog
header-img: img/home-bg.jpg
email: gesturewei@gmail.com
description: "My GitHub Blog - Use Clean Blog as a template"
baseurl: "/gesturewei.github.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
